Test

In [1]:
import numpy as np
import scipy.stats as scp
import matplotlib.pyplot as plt

In [36]:
%matplotlib inline

In [51]:
states = np.arange(0,11,1)

In [58]:
statetransitions = np.zeros((len(states),len(states)))
statetransitions[0][0] = 0.9
statetransitions[0][1] = 0.1
statetransitions[10][-1] = 0.9
statetransitions[10][-2] = 0.1

for i in range(len(states)-2):
        
    statetransitions[i+1][0] = 0.1
    statetransitions[i+1][1] = 0.8
    statetransitions[i+1][2] = 0.1
    statetransitions[i+1] = np.roll(statetransitions[i+1],i)
    

In [59]:
statetransitions

array([[0.9, 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.1, 0.8, 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0.1, 0.8, 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.1, 0.8, 0.1, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.1, 0.8, 0.1, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.1, 0.8, 0.1, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.1, 0.8, 0.1, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.1, 0.8, 0.1, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.1, 0.8, 0.1, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.1, 0.8, 0.1],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.1, 0.9]])

In [24]:
a = np.array([[1,2,3],[4,5,6]])

In [27]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# np.roll(a,2,axis=1)

array([[2, 3, 1],
       [5, 6, 4]])